function toSlug(value = '') {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'generated-module';
}

export function buildModuleArtifact(request, context = {}) {
  const moduleName = `${toSlug(request)}.js`;
  const lines = [
    `// Generated by Zayvora code intelligence`,
    `// Prompt: ${request}`,
    `export function createModule(seed = 0) {`,
    `  const state = { seed, patterns: ${JSON.stringify(context.patterns || [])} };`,
    `  return {`,
    `    run(input = {}) {`,
    `      return { ...input, seed: state.seed, patterns: state.patterns, generatedAt: new Date().toISOString() };`,
    `    }`,
    `  };`,
    `}`
  ];

  return {
    fileName: moduleName,
    content: `${lines.join('\n')}\n`,
    language: 'javascript'
  };
}
