#!/bin/bash
# scripts/quality-report.sh
# Antigravity Agent: Daily Quality Status Generator

echo "# 📊 Zayvora Quality Report - $(date)"
echo "----------------------------------------"

# 1. Code Quality (Lint)
echo "## Code Quality"
LINT_RESULT=$(npm run lint 2>&1 || true)
LINT_ERRORS=$(echo "$LINT_RESULT" | grep "error" | wc -l)
echo "- ESLint Errors: $LINT_ERRORS (target: 0)"

# 2. Security (Audit)
echo "## Security"
AUDIT_RESULT=$(npm audit --json 2>/dev/null || true)
VULNS=$(echo "$AUDIT_RESULT" | jq '.metadata.vulnerabilities.total' 2>/dev/null || echo "0")
echo "- Vulnerabilities: $VULNS (target: 0)"

# 3. Build Status
echo "## Build Status"
npm run build > /dev/null 2>&1 && echo "- Build: ✅ SUCCESS" || echo "- Build: ❌ FAILED"

echo "----------------------------------------"
echo "Report generated by Antigravity Agent"
